// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// beta_work_cpp
Rcpp::List beta_work_cpp(const NumericVector& y, const NumericVector& eta, const double phi);
RcppExport SEXP _SelectBoost_beta_beta_work_cpp(SEXP ySEXP, SEXP etaSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_work_cpp(y, eta, phi));
    return rcpp_result_gen;
END_RCPP
}
// beta_phi_update_cpp
double beta_phi_update_cpp(double phi, const NumericVector& mu, const NumericVector& y, int maxit);
RcppExport SEXP _SelectBoost_beta_beta_phi_update_cpp(SEXP phiSEXP, SEXP muSEXP, SEXP ySEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_phi_update_cpp(phi, mu, y, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SelectBoost_beta_beta_work_cpp", (DL_FUNC) &_SelectBoost_beta_beta_work_cpp, 3},
    {"_SelectBoost_beta_beta_phi_update_cpp", (DL_FUNC) &_SelectBoost_beta_beta_phi_update_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SelectBoost_beta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
