# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_work_cpp <- function(y, eta, phi) {
    .Call(`_SelectBoost_beta_beta_work_cpp`, y, eta, phi)
}

beta_phi_update_cpp <- function(phi, mu, y, maxit) {
    .Call(`_SelectBoost_beta_beta_phi_update_cpp`, phi, mu, y, maxit)
}

